CREATE TABLE [dbo_Programme_Base] (
  [Id] LONG,
  [OriginalId] LONG,
  [Created] DATETIME,
  [Modified] DATETIME,
  [Submitted] DATETIME,
  [CreatedBy] VARCHAR (100),
  [ModifiedBy] VARCHAR (100),
  [SubmittedBy] VARCHAR (100),
  [FormType] VARCHAR (13),
  [FormStatus] VARCHAR (50),
  [Checklist_Q1] VARCHAR (10),
  [Checklist_Q2] VARCHAR (10),
  [Checklist_Q3] VARCHAR (10),
  [Checklist_Q4] VARCHAR (10),
  [Checklist_Q5] VARCHAR (10),
  [Checklist_Q6] VARCHAR (10),
  [Checklist_Q7] VARCHAR (10),
  [Checklist_Q8] VARCHAR (10),
  [Checklist_Q9] VARCHAR (10),
  [Checklist_Q10] VARCHAR (10),
  [Checklist_Q11] VARCHAR (10),
  [Checklist_Q12] VARCHAR (10),
  [Checklist_Q13] VARCHAR (10),
  [Checklist_Q14] VARCHAR (10),
  [Checklist_Q15] VARCHAR (10),
  [Checklist_Q16] VARCHAR (10),
  [Checklist_Q17] VARCHAR (10),
  [Checklist_Q18] VARCHAR (10),
  [Checklist_Q19] VARCHAR (10),
  [Checklist_Comments] LONGTEXT,
  [ModifyProposalType] VARCHAR (20),
  [ModifySummary] LONGTEXT,
  [InvolvesAnySpecialChanges] BIT,
  [ProgrammeStem] VARCHAR (100),
  [ProgrammeNamedDiscipline] VARCHAR (100),
  [ProgrammeCode] VARCHAR (10),
  [ProgrammeTitle] VARCHAR (200),
  [AwardTitleStem] VARCHAR (100),
  [AwardNamedDiscipline] VARCHAR (100),
  [NFQLevel] LONG,
  [AwardType] VARCHAR (10),
  [TotalCredits] LONG,
  [IncludesExitAwards] BIT,
  [ExitAwardsDetail] LONGTEXT,
  [Submission_Reason1] BIT,
  [Submission_Reason2] BIT,
  [Submission_Reason3] BIT,
  [Submission_Reason4] BIT,
  [Submission_Reason5] BIT,
  [Submission_Reason6] BIT,
  [Submission_Reason7] BIT,
  [Submission_Reason8] BIT,
  [Submission_ReasonOther] BIT,
  [Rationale] LONGTEXT,
  [Faculty] VARCHAR (10),
  [Department] VARCHAR (10),
  [Implications_ByRequested] BIT,
  [Implications_ByDropped] BIT,
  [Implications_ToDropped] BIT,
  [Implications_Detail] LONGTEXT,
  [CollaborativeProgramme] BIT,
  [CollaborativeProgrammeType] VARCHAR (50),
  [CollaborativePartners] LONGTEXT,
  [PartnershipAgreementConsidered] BIT,
  [PartnershipAgreementStatement] LONGTEXT,
  [PartnershipAgreementSigned] BIT,
  [ExternalPartnersContributingModules] LONGTEXT,
  [DeliveryMode] VARCHAR (10),
  [DeliveryPrimary] VARCHAR (20),
  [DeliveryOther_Blended] BIT,
  [DeliveryOther_DistanceEducation] BIT,
  [DeliveryOther_ELearning] BIT,
  [DeliveryOther_EveningProgramme] BIT,
  [DeliveryOther_OffCampus] BIT,
  [ISCED] VARCHAR (10),
  [HEAType] VARCHAR (10),
  [CAOCode] VARCHAR (20),
  [TeacherEducationType] VARCHAR (100),
  [ProgrammeStart] VARCHAR (10),
  [AcademicYearCommencement] VARCHAR (10),
  [SemesterCommencement] VARCHAR (10),
  [MultiYearImplementation] VARCHAR (100),
  [ModificationsImplemented] BIT,
  [ImplementationPlanAgreed] BIT,
  [CentralSchedulingRequired] BIT,
  [Knowledge] LONGTEXT,
  [KnowHowSkill] LONGTEXT,
  [CompetenceContextRole] LONGTEXT,
  [CompetenceLearningToLearn] LONGTEXT,
  [CompetenceInsight] LONGTEXT,
  [LearningEnvironment] LONGTEXT,
  [StructureType] VARCHAR (10),
  [CourseDivided] BIT,
  [YearPartTwoBegins] VARCHAR (10),
  [GraduationExamBoard] VARCHAR (10),
  [NotesOnStructure] LONGTEXT,
  [PathwayName] VARCHAR (200),
  [CoreTaughtElementCredits] VARCHAR (10),
  [CoreTaughtElectiveElementCredits] VARCHAR (10),
  [CoreResearchElementCredits] VARCHAR (10),
  [CoOpPlacementRequired] BIT,
  [CoOpPlacementDetails] LONGTEXT,
  [GeneralEntryQualifications] LONGTEXT,
  [RPLEntryRequirements] LONGTEXT,
  [GardaVettingRequired] BIT,
  [ConformsToAcademicRegulations] BIT,
  [SpecificRegulations] LONGTEXT,
  [IsVariantProgramme] BIT,
  [CourseDirector] VARCHAR (100),
  [HumanResourcesRequired] BIT,
  [HumanResourcesDetail] LONGTEXT,
  [PhysicalResourcesRequired] BIT,
  [PhysicalResourcesDetail] LONGTEXT,
  [ITResourcesRequired] BIT,
  [ITResourcesDetail] LONGTEXT,
  [LibraryResourcesRequired] BIT,
  [LibraryResourcesDetail] LONGTEXT,
  [AcademicRegistryConsulted] BIT,
  [AcademicRegistryConsultationDetails] LONGTEXT,
  [ResourcesNotes] LONGTEXT,
  [Retire_Rationale] LONGTEXT,
  [Retire_AcademicYear] VARCHAR (10),
  [Retire_Semester] VARCHAR (10)
)
